import argparse
import sys

from ai_engineer_cli.config import load_config
from ai_engineer_cli.llm_client import LLMClient
from ai_engineer_cli.prompt_templates import (
    list_templates,
    load_template,
    render_template,
)
from ai_engineer_cli.response_format import (
    ResponseFormat,
    ResponseLanguage,
    build_system_prompt,
    validate_json_response,
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="ai-engineer-cli",
        description="CLI tool for working with LLMs as an engineering assistant.",
    )

    parser.add_argument(
        "prompt",
        nargs="?",
        type=str,
        help="Prompt to send to the LLM.",
    )

    parser.add_argument(
        "--format",
        choices=[item.value for item in ResponseFormat],
        default=ResponseFormat.TEXT.value,
        help="Response format: text, markdown, or json.",
    )

    parser.add_argument(
        "--language",
        choices=[item.value for item in ResponseLanguage],
        default=ResponseLanguage.RU.value,
        help="Response language: ru or en.",
    )

    parser.add_argument(
        "--max-output-tokens",
        type=int,
        default=None,
        help="Maximum number of output tokens generated by the model.",
    )

    parser.add_argument(
        "--stop-instruction",
        type=str,
        default=None,
        help="Instruction that tells the model how to finish the answer.",
    )

    parser.add_argument(
        "--template",
        type=str,
        default=None,
        help="Prompt template name from the prompts directory.",
    )

    parser.add_argument(
        "--list-templates",
        action="store_true",
        help="List available prompt templates and exit.",
    )

    parser.add_argument(
        "--no-separator",
        action="store_true",
        help="Print raw response without visual separators.",
    )

    parser.add_argument(
        "--temperature",
        type=float,
        default=None,
        help="Sampling temperature. Lower values are more deterministic; higher values are more diverse.",
    )

    return parser


def print_response(response: str, use_separator: bool = True) -> None:
    if not use_separator:
        print(response)
        return

    separator = "─" * 60

    print()
    print(separator)
    print("AI RESPONSE")
    print(separator)
    print()
    print(response)
    print()
    print(separator)


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    try:
        if args.list_templates:
            templates = list_templates()

            if not templates:
                print("No templates found.")
                return

            print("Available templates:")
            for template in templates:
                print(f"- {template}")

            return

        if not args.prompt:
            raise ValueError("Prompt is required unless --list-templates is used.")

        if args.max_output_tokens is not None and args.max_output_tokens <= 0:
            raise ValueError("--max-output-tokens must be greater than 0.")

        if args.temperature is not None and not 0 <= args.temperature <= 2:
            raise ValueError("--temperature must be between 0 and 2.")

        response_format = ResponseFormat(args.format)
        response_language = ResponseLanguage(args.language)

        system_prompt = build_system_prompt(
            response_format=response_format,
            language=response_language,
            max_output_tokens=args.max_output_tokens,
            stop_instruction=args.stop_instruction,
        )

        prompt = args.prompt

        if args.template:
            template_text = load_template(args.template)
            prompt = render_template(
                template_text=template_text,
                user_input=args.prompt,
            )

        config = load_config()
        llm_client = LLMClient(config)

        response = llm_client.ask(
            prompt=prompt,
            system_prompt=system_prompt,
            max_output_tokens=args.max_output_tokens,
            temperature=args.temperature,
        )

        if response_format == ResponseFormat.JSON:
            validate_json_response(response)

        print_response(
            response=response,
            use_separator=not args.no_separator,
        )

    except Exception as error:
        print(f"Error: {error}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()