import argparse
import sys

from ai_engineer_cli.config import load_config
from ai_engineer_cli.llm_client import LLMClient
from ai_engineer_cli.response_format import (
    ResponseFormat,
    build_system_prompt,
    validate_json_response,
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="ai-engineer-cli",
        description="CLI tool for working with LLMs as an engineering assistant.",
    )

    parser.add_argument(
        "prompt",
        type=str,
        help="Prompt to send to the LLM.",
    )

    parser.add_argument(
        "--format",
        choices=[item.value for item in ResponseFormat],
        default=ResponseFormat.TEXT.value,
        help="Response format: text, markdown, or json.",
    )

    parser.add_argument(
        "--max-output-tokens",
        type=int,
        default=None,
        help="Maximum number of output tokens generated by the model.",
    )

    parser.add_argument(
        "--stop-instruction",
        type=str,
        default=None,
        help="Instruction that tells the model how to finish the answer.",
    )

    return parser


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    try:
        if args.max_output_tokens is not None and args.max_output_tokens <= 0:
            raise ValueError("--max-output-tokens must be greater than 0.")

        response_format = ResponseFormat(args.format)

        system_prompt = build_system_prompt(
            response_format=response_format,
            max_output_tokens=args.max_output_tokens,
            stop_instruction=args.stop_instruction,
        )

        config = load_config()
        llm_client = LLMClient(config)

        response = llm_client.ask(
            prompt=args.prompt,
            system_prompt=system_prompt,
            max_output_tokens=args.max_output_tokens,
        )

        if response_format == ResponseFormat.JSON:
            validate_json_response(response)

        print(response)

    except Exception as error:
        print(f"Error: {error}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()