import argparse
import sys

from ai_engineer_cli.terminal_ui import print_cli_response
from ai_engineer_cli.agent import Agent, MessageStore, SummaryManager
from ai_engineer_cli.config import load_config
from ai_engineer_cli.llm_client import LLMClient
from ai_engineer_cli.prompt_templates import (
    list_templates,
    load_template,
    render_template,
)
from ai_engineer_cli.response_format import (
    ResponseFormat,
    ResponseLanguage,
    build_system_prompt,
    validate_json_response,
)


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="ai-engineer-cli",
        description="CLI tool for working with LLMs as an engineering assistant.",
    )

    parser.add_argument(
        "prompt",
        nargs="?",
        type=str,
        help="Prompt to send to the LLM.",
    )

    parser.add_argument(
        "--format",
        choices=[item.value for item in ResponseFormat],
        default=ResponseFormat.TEXT.value,
        help="Response format: text, markdown, or json.",
    )

    parser.add_argument(
        "--language",
        choices=[item.value for item in ResponseLanguage],
        default=ResponseLanguage.RU.value,
        help="Response language: ru or en.",
    )

    parser.add_argument(
        "--max-output-tokens",
        type=int,
        default=None,
        help="Maximum number of output tokens generated by the model.",
    )

    parser.add_argument(
        "--stop-instruction",
        type=str,
        default=None,
        help="Instruction that tells the model how to finish the answer.",
    )

    parser.add_argument(
        "--template",
        type=str,
        default=None,
        help="Prompt template name from the prompts directory.",
    )

    parser.add_argument(
        "--list-templates",
        action="store_true",
        help="List available prompt templates and exit.",
    )

    parser.add_argument(
        "--no-separator",
        action="store_true",
        help="Print raw response without visual separators.",
    )

    parser.add_argument(
        "--no-metadata",
        action="store_true",
        help="Do not print response metadata such as model, duration, tokens, and estimated cost.",
    )

    parser.add_argument(
        "--temperature",
        type=float,
        default=None,
        help="Sampling temperature. Lower values are more deterministic; higher values are more diverse.",
    )

    parser.add_argument(
        "--model",
        type=str,
        default=None,
        help="Model name. Overrides OPENAI_MODEL from .env.",
    )

    parser.add_argument(
        "--agent",
        action="store_true",
        help="Run request through Agent runtime instead of direct LLMClient call.",
    )

    parser.add_argument(
        "--conversation-id",
        type=str,
        default="default",
        help="Conversation id for persistent agent history.",
    )

    parser.add_argument(
        "--clear-history",
        action="store_true",
        help="Clear stored history for the selected conversation and exit.",
    )

    parser.add_argument(
        "--show-context-stats",
        action="store_true",
        help="Show estimated token usage for agent context.",
    )

    parser.add_argument(
        "--context-token-limit",
        type=int,
        default=None,
        help="Warn when estimated full context tokens exceed this limit.",
    )

    parser.add_argument(
        "--use-summary",
        action="store_true",
        help="Enable summary-based context compression for agent mode.",
    )

    parser.add_argument(
        "--recent-messages",
        type=int,
        default=6,
        help="Number of recent messages to keep as-is when summary compression is enabled.",
    )

    parser.add_argument(
        "--summary-every",
        type=int,
        default=10,
        help="Compress history into summary when stored message count reaches this value.",
    )

    return parser


def print_response(
    response: str,
    use_separator: bool = True,
    metadata: dict[str, str] | None = None,
    show_metadata: bool = True,
) -> None:
    if not use_separator:
        print(response)

        if metadata and show_metadata:
            print()
            print_metadata(metadata)

        return

    separator = "─" * 60

    print()
    print(separator)
    print("AI RESPONSE")
    print(separator)
    print()
    print(response)
    print()

    if metadata and show_metadata:
        print(separator)
        print("METADATA")
        print(separator)
        print_metadata(metadata)
        print()

    print(separator)


def print_metadata(metadata: dict[str, str]) -> None:
    for key, value in metadata.items():
        print(f"{key}: {value}")


def main() -> None:
    parser = build_parser()
    args = parser.parse_args()

    try:
        if args.list_templates:
            templates = list_templates()

            if not templates:
                print("No templates found.")
                return

            print("Available templates:")
            for template in templates:
                print(f"- {template}")

            return

        if not args.prompt and not args.clear_history:
            raise ValueError("Prompt is required unless --list-templates or --clear-history is used.")

        if args.max_output_tokens is not None and args.max_output_tokens <= 0:
            raise ValueError("--max-output-tokens must be greater than 0.")

        if args.context_token_limit is not None and args.context_token_limit <= 0:
            raise ValueError("--context-token-limit must be greater than 0.")

        if args.context_token_limit is not None and not args.agent:
            raise ValueError("--context-token-limit can only be used with --agent.")

        if args.temperature is not None and not 0 <= args.temperature <= 2:
            raise ValueError("--temperature must be between 0 and 2.")

        if args.show_context_stats and not args.agent:
            raise ValueError("--show-context-stats can only be used with --agent.")

        if args.use_summary and not args.agent:
            raise ValueError("--use-summary can only be used with --agent.")

        if args.recent_messages <= 0:
            raise ValueError("--recent-messages must be greater than 0.")

        if args.summary_every <= 0:
            raise ValueError("--summary-every must be greater than 0.")

        if args.recent_messages >= args.summary_every:
            raise ValueError("--recent-messages must be less than --summary-every.")

        response_format = ResponseFormat(args.format)
        response_language = ResponseLanguage(args.language)

        system_prompt = build_system_prompt(
            response_format=response_format,
            language=response_language,
            max_output_tokens=args.max_output_tokens,
            stop_instruction=args.stop_instruction,
        )

        prompt = args.prompt

        if args.template:
            template_text = load_template(args.template)
            prompt = render_template(
                template_text=template_text,
                user_input=args.prompt,
            )

        config = load_config()
        llm_client = LLMClient(config)

        context_token_stats = None

        if args.agent:
            message_store = MessageStore(conversation_id=args.conversation_id)

            summary_manager = SummaryManager(llm_client=llm_client) if args.use_summary else None

            agent = Agent(
                llm_client=llm_client,
                system_prompt=system_prompt,
                message_store=message_store,
                summary_manager=summary_manager,
                use_summary=args.use_summary,
                recent_messages=args.recent_messages,
                summary_every=args.summary_every,
            )

            if args.clear_history:
                agent.clear_history()
                print(f"History cleared for conversation: {args.conversation_id}")
                return

            llm_response = agent.run(
                user_input=prompt,
                model=args.model,
                max_output_tokens=args.max_output_tokens,
                temperature=args.temperature,
            )

            context_token_stats = agent.last_context_token_stats

        else:
            llm_response = llm_client.ask(
                prompt=prompt,
                system_prompt=system_prompt,
                model=args.model,
                max_output_tokens=args.max_output_tokens,
                temperature=args.temperature,
            )

        if response_format == ResponseFormat.JSON:
            validate_json_response(llm_response.text)

        metadata = {
            "model": llm_response.model,
            "duration": f"{llm_response.duration_seconds:.2f}s",
            "tokens": (
                f"{llm_response.input_tokens} input / "
                f"{llm_response.output_tokens} output / "
                f"{llm_response.total_tokens} total"
            ),
            "estimated cost": (
                f"${llm_response.estimated_cost_usd:.8f}"
                if llm_response.estimated_cost_usd is not None
                else "unknown"
            ),
        }

        if args.agent:
            metadata["summary enabled"] = str(args.use_summary)

            if args.use_summary:
                metadata["recent messages"] = str(args.recent_messages)
                metadata["summary every"] = str(args.summary_every)

        if args.show_context_stats and context_token_stats:
            metadata.update(
                {
                    "context messages": str(context_token_stats.full_context_messages_count),
                    "history messages": str(context_token_stats.history_messages_count),
                    "estimated current request tokens": str(
                        context_token_stats.current_request_tokens
                    ),
                    "estimated history tokens": str(context_token_stats.history_tokens),
                    "estimated full context tokens": str(
                        context_token_stats.full_context_tokens
                    ),
                }
            )

        if args.context_token_limit is not None and context_token_stats:
            if context_token_stats.full_context_tokens > args.context_token_limit:
                metadata["context warning"] = (
                    f"estimated context tokens exceeded limit "
                    f"({context_token_stats.full_context_tokens} > "
                    f"{args.context_token_limit})"
                )

        print_cli_response(
            response=llm_response.text,
            metadata=metadata,
            user_input=prompt,
            mode="agent" if args.agent else "direct",
            use_boxes=not args.no_separator,
            show_metadata=not args.no_metadata,
        )

    except Exception as error:
        print(f"Error: {error}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()